<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; text-align: center; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .info-row { display: flex; justify-content: space-between; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #333; color: white; padding: 8px; text-align: left; }
        td { padding: 8px; border: 1px solid #ddd; }
        .notes { margin-top: 20px; padding: 10px; background: #f9f9f9; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
    </style>
</head>
<body>

    <div class="header">
        <h1>🏥 MediCare Hospital</h1>
        <p>Medical Prescription</p>
    </div>

    <div class="info-row">
        <div>
            <strong>Doctor:</strong> Dr. {{ $prescription->doctor->user->name }}<br>
            <strong>Date:</strong> {{ $prescription->created_at->format('d M Y') }}
        </div>
        <div>
            <strong>Patient:</strong> {{ $prescription->patient->name }}<br>
            <strong>Prescription #:</strong> {{ $prescription->id }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Medicine</th>
                <th>Dosage</th>
                <th>Duration</th>
            </tr>
        </thead>
        <tbody>
            @foreach($prescription->medicines as $index => $medicine)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $medicine['name'] }}</td>
                    <td>{{ $medicine['dosage'] }}</td>
                    <td>{{ $medicine['duration'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if($prescription->notes)
        <div class="notes">
            <strong>Doctor Notes:</strong><br>
            {{ $prescription->notes }}
        </div>
    @endif

    <div class="footer">
        <p>Generated by MediCare Hospital System</p>
    </div>

</body>
</html>